version : '3.1'

# MongoDB, Postgres, Redis, Elasticsearch, Kibana, Mysql, Postgres
services: 
  mongo: 
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
    - 27017:27017
    volumes:
      - mongo_data:/data/db # Persistent storage for MongoDB
     
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persistent storage for RabbitMQ

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: riders_db # Change this to your preferred database name
    ports:
      - 5433:5432 # PostgreSQL default port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent storage for PostgreSQL

volumes:
  mongo_data: # Named volume for MongoDB
  rabbitmq_data: # Named volume for RabbitMQ
  postgres_data: # Named volume for PostgreSQL